version: "0.1.0"
summary:
  title: "Subtask Demo"
  description: "An example of subtasks in CodeRoad"
config:
  testRunner:
    command: ./node_modules/.bin/mocha
    args: 
      filter: --grep
      tap: --reporter=mocha-tap-reporter
    director: .coderoad
    setup:
      commits: 410bd4f
      commands: npm install
  repo: 
    uri: https://github.com/shmck/coderoad-tutorial-subtask-demo
    branch: v0.1.0
  dependencies:
    - name: node
      version: ">=10"
levels:
  - id: L1
    config: {}
    steps:
      - id: L1S1
        setup:
          files:
            - src/add.js
          commits: []
        solution:
          files:
            - src/add.js
          commits: []