env:
  es6: true
  node: true
  commonjs: true
  mocha: true
extends:
  - airbnb-base
  - plugin:mocha/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prefer-arrow-callback: off
  func-names: off
plugins:
  - mocha